{
    "start": 1416614400,
    "end": 1479772800,
    "step": 86400,
    "flags": [
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1433433820000,
                    "text": "A new update is now available : 04-06-2015 #15",
                    "title": "A"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1400338232000,
                    "text": "Price drop",
                    "title": "B"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1398720550000,
                    "text": "Day One: Garry's Incident 90% off",
                    "title": "C"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1387731783000,
                    "text": "Contest",
                    "title": "D"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1387464657000,
                    "text": "Holidays Trees HUNT Contest",
                    "title": "E"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1384972501000,
                    "text": "Win 1 out of 50 Day One: Garry's Incident Steam keys",
                    "title": "F"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1384877277000,
                    "text": "Get 33% off Day One in Steam Weekly Sale!",
                    "title": "G"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1384875389000,
                    "text": "Here is the contest for the launch of our new Free DLC",
                    "title": "H"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1384869249000,
                    "text": "A new update is now available : 19-11-2013 #13",
                    "title": "I"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1384797034000,
                    "text": "Major update incoming for tomorrow with fixes and a Free DLC: The Survivor Challenge",
                    "title": "J"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1382719120000,
                    "text": "The Trading Cards are now available.",
                    "title": "K"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1382535992000,
                    "text": "Announcement #2 - 23-10-2013 -",
                    "title": "L"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1382041994000,
                    "text": "A new update is now available : 17-10-2013 #12",
                    "title": "M"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1381859355000,
                    "text": "25 free Steam Keys For Day One : Garry's Incident",
                    "title": "N"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1381847363000,
                    "text": "A new update is now available : 15-10-2013 #11",
                    "title": "O"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1381419069000,
                    "text": "A new mode available soon: Survival",
                    "title": "P"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1381186740000,
                    "text": "A new update is now available : 07-10-2013 #9",
                    "title": "Q"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1380913428000,
                    "text": "A new video: \"Let's have a look\" by Kotaku",
                    "title": "R"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1380831948000,
                    "text": "A new update is now available : 03-10-2013 #8",
                    "title": "S"
                }
            ]
        },
        {
            "type": "flags",
            "shape": "flag",
            "width": 14,
            "color": "#8BC34A",
            "data": [
                {
                    "x": 1380743998000,
                    "text": "A new update is now available : 01-10-2013 #7",
                    "title": "T"
                }
            ]
        }
    ],
    "players": [
        null,
        5,
        8,
        4,
        4,
        5,
        7,
        7,
        8,
        5,
        4,
        6,
        7,
        4,
        7,
        6,
        7,
        4,
        3,
        6,
        6,
        9,
        10,
        6,
        9,
        8,
        6,
        9,
        9,
        7,
        11,
        8,
        6,
        8,
        8,
        12,
        10,
        9,
        11,
        7,
        9,
        10,
        8,
        6,
        6,
        6,
        5,
        7,
        7,
        4,
        5,
        5,
        5,
        5,
        4,
        4,
        5,
        4,
        10,
        12,
        10,
        11,
        8,
        15,
        15,
        10,
        6,
        7,
        6,
        5,
        7,
        8,
        5,
        6,
        7,
        5,
        7,
        7,
        9,
        5,
        9,
        10,
        5,
        11,
        7,
        8,
        4,
        6,
        6,
        6,
        7,
        6,
        7,
        5,
        6,
        6,
        4,
        5,
        5,
        8,
        4,
        5,
        6,
        5,
        7,
        6,
        9,
        5,
        5,
        5,
        4,
        5,
        7,
        6,
        5,
        5,
        3,
        3,
        3,
        6,
        8,
        8,
        8,
        8,
        7,
        8,
        7,
        7,
        7,
        9,
        6,
        6,
        6,
        4,
        5,
        5,
        4,
        4,
        6,
        4,
        4,
        6,
        6,
        3,
        3,
        4,
        3,
        4,
        7,
        4,
        3,
        3,
        4,
        4,
        5,
        4,
        4,
        4,
        3,
        5,
        4,
        4,
        3,
        4,
        3,
        3,
        3,
        4,
        4,
        3,
        5,
        4,
        5,
        4,
        5,
        6,
        5,
        4,
        4,
        4,
        5,
        5,
        7,
        5,
        13,
        17,
        16,
        14,
        15,
        15,
        16,
        17,
        6,
        5,
        9,
        8,
        6,
        7,
        5,
        8,
        5,
        5,
        5,
        7,
        7,
        5,
        6,
        5,
        6,
        4,
        5,
        4,
        7,
        6,
        4,
        6,
        6,
        7,
        6,
        7,
        4,
        5,
        6,
        6,
        6,
        3,
        5,
        6,
        5,
        3,
        5,
        5,
        7,
        5,
        6,
        4,
        4,
        3,
        4,
        5,
        5,
        6,
        5,
        6,
        4,
        6,
        4,
        9,
        11,
        10,
        10,
        12,
        11,
        10,
        12,
        9,
        6,
        7,
        6,
        8,
        7,
        7,
        5,
        7,
        7,
        6,
        6,
        9,
        5,
        7,
        5,
        6,
        8,
        5,
        7,
        6,
        8,
        7,
        7,
        6,
        7,
        6,
        6,
        6,
        4,
        7,
        5,
        7,
        7,
        7,
        5,
        4,
        5,
        3,
        5,
        4,
        3,
        4,
        4,
        4,
        6,
        6,
        3,
        3,
        5,
        5,
        4,
        4,
        5,
        5,
        8,
        9,
        9,
        9,
        11,
        18,
        14,
        11,
        6,
        5,
        5,
        4,
        7,
        8,
        5,
        6,
        3,
        5,
        4,
        4,
        5,
        5,
        6,
        4,
        3,
        4,
        4,
        5,
        5,
        5,
        7,
        6,
        5,
        7,
        8,
        6,
        5,
        5,
        5,
        4,
        5,
        5,
        5,
        4,
        5,
        3,
        3,
        6,
        3,
        4,
        4,
        4,
        7,
        5,
        5,
        6,
        3,
        3,
        5,
        4,
        5,
        6,
        6,
        3,
        4,
        6,
        6,
        4,
        4,
        5,
        7,
        13,
        12,
        16,
        13,
        14,
        17,
        10,
        8,
        6,
        7,
        5,
        7,
        6,
        4,
        5,
        7,
        10,
        7,
        7,
        8,
        9,
        9,
        12,
        8,
        8,
        9,
        9,
        7,
        7,
        8,
        5,
        7,
        4,
        5,
        5,
        7,
        8,
        8,
        7,
        8,
        6,
        8,
        6,
        7,
        5,
        6,
        10,
        6,
        5,
        7,
        7,
        5,
        7,
        8,
        6,
        4,
        6,
        4,
        4,
        7,
        7,
        8,
        4,
        4,
        6,
        4,
        5,
        5,
        5,
        4,
        4,
        5,
        3,
        5,
        5,
        4,
        7,
        12,
        9,
        9,
        10,
        12,
        12,
        8,
        8,
        5,
        5,
        6,
        5,
        4,
        5,
        5,
        6,
        4,
        5,
        4,
        7,
        4,
        4,
        3,
        4,
        5,
        4,
        4,
        3,
        3,
        5,
        5,
        5,
        6,
        3,
        4,
        4,
        3,
        2,
        3,
        5,
        3,
        5,
        4,
        3,
        4,
        4,
        4,
        4,
        4,
        2,
        3,
        3,
        3,
        6,
        5,
        3,
        3,
        3,
        3,
        6,
        4,
        3,
        4,
        9,
        9,
        9,
        7,
        11,
        8,
        8,
        5,
        3,
        3,
        4,
        4,
        5,
        4,
        3,
        2,
        6,
        4,
        4,
        5,
        6,
        4,
        4,
        3,
        4,
        5,
        4,
        3,
        3,
        3,
        3,
        4,
        4,
        7,
        5,
        3,
        4,
        3,
        5,
        5,
        5,
        4,
        6,
        4,
        3,
        4,
        4,
        5,
        2,
        6,
        3,
        3,
        3,
        3,
        4,
        4,
        4,
        2,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        6,
        3,
        8,
        5,
        7,
        4,
        5,
        3,
        3,
        4,
        5,
        5,
        6,
        7,
        7,
        6,
        6,
        10,
        6,
        4,
        6,
        7,
        4,
        3,
        3,
        4,
        4,
        3,
        4,
        4,
        4,
        4,
        3,
        3,
        2,
        5,
        3,
        3,
        3,
        2,
        2,
        2,
        5,
        3,
        4,
        4,
        3,
        3,
        3,
        4,
        4,
        3,
        5,
        3,
        3,
        3,
        2,
        3,
        3,
        5,
        3,
        4,
        3,
        3,
        4,
        3,
        2,
        4,
        2,
        2,
        2,
        2,
        3,
        2,
        3,
        2,
        3,
        2,
        2,
        2,
        3,
        2,
        3,
        4,
        2,
        5,
        5,
        6,
        7,
        3,
        4,
        3,
        3,
        3,
        5,
        1,
        4,
        2,
        2,
        3,
        3,
        2,
        4,
        1,
        3,
        2,
        2,
        3,
        4,
        2,
        2,
        2,
        2,
        2,
        3,
        3,
        2,
        2,
        4,
        4,
        2,
        4,
        2,
        3,
        2,
        2,
        3,
        3,
        3,
        3,
        3,
        2,
        3,
        3,
        2,
        4,
        4,
        3,
        2,
        3,
        1,
        3,
        3,
        3,
        2
    ]
}